### ISSUE TITLE
Feature Request: Option to add custom words

### ISSUE THREAD

**Issue by SayantaBhar** [dperelman/codenames.plus#8]
It would be great if we can add custom words and play with those.

P.S: Not sure how active is the original codebase from where it has been forked hence askig here also. Thanks in advance

**Comment by dperelman** [comment]
(Yeah, the upstream looks pretty dead. That's part of why I enabled issues on my fork.)

I see you also commented on jbowens/codenames which handles custom word lists and has a lot more default word lists. There's also Joooop#18 which adds some more default work lists.

Anyway, if you make a PR to add custom word list support, I'll merge it. I think the actual backend part should be fairly straightforward; the UI will need a bit of work to make the work list selection area a bit larger without looking weird (maybe a +/- to show/hide it?). I haven't put much thought into word lists because the people I play with are really only interested in the default one, so I'm not in a rush to do it myself, but I'll probably get around to it eventually if you don't.

**Comment by SayantaBhar** [comment]
https://github.com/jbowens/codenames has issue of its own and also, we like some features (like showing team etc) here.
 https://github.com/Joooop/codenames.plus/pull/18 added words from different non-English languages which is not useful to me.
For now, I have added a new button under which I have added all the words we wanted and hosting separately (cause my group wanted a feature like scoreboard also so it was easier and quicker to build those features and then host it separately). Didn't get time to put my head around custom word addition especially the UI. If I get time, I will work on it and submit a PR. Thanks.

**Comment by dperelman** [comment]
Yeah, I decided to modify codenames.plus instead of jbowens/codenames because it was closer to already doing what I wanted. I was mostly pointing to it because I figured if you want to improve the wordlist support, feature parity with jbowens/codenames may be a reasonable goal and it looks like Joooop#18 reworks things so having a lot of wordlists works better, at least on the server side.

Where's your wordlist from? It looks pretty generic, just a lot bigger than the standard wordlist.

I hadn't thought of a scoreboard as my group usually reshuffles teams each game, but I'd accept a PR for it.

I also just migrated my local TODO text file into GitHub issues so you can see what I'm planning based on issues my group has run into.

**Comment by SayantaBhar** [comment]
My word list is generic googled simple words, we just wanted to have more words otherwise same words were coming repetitively.
Will raise the PR against your branch for the scoreboard.

**Comment by dperelman** [comment]
BTW, the existing NLSS word pack appears to be some other group's custom word list ([discussion on Reddit](https://www.reddit.com/r/NLSSCircleJerk/comments/94wl3o/i_made_codenamesplus_and_added_some_qol/), I guess it's the group that wrote codenames.plus in the first place). I think adding your own more generic word list seems reasonable, although I wouldn't make it default on my version.

**Comment by dperelman** [comment]
16622ad98469d7f3cad02f4cb9be3edc84295c32 factors out the word lists into the settings, so now you could have a card pack that you don't push upstream by adding a `local_settings.js` file like
```js
var config = module.exports = {
  defaultCardPacks: ["Local-only Pack"],
  additionalCardPacks: [
    {name: "Local-only Pack", filename: "./server/local-words.txt"},
  ],
}
```
as well as more easily add additional card packs just by adding them to `settings.js`.

Letting users just paste in a custom word list is still not implemented, but shouldn't be too hard to add...

**Comment by dperelman** [comment]
I finally actually added support for this with 242039b.

There's now a setting `allowCustomCardPack` (enabled by default) which adds "Custom" to the bottom of the list of card packs. When enabled, a text area appears where you can type/paste in a list of words (new lines, comma, and semicolon are all accepted as delimiters... so words can't contain those characters). On "New Game", the custom word list is updated from the browser of the user who clicks "New Game" (if the custom word pack is enabled, otherwise the list is cleared). If there are not enough words (since you can select just "Custom" and put in fewer than 25 words) a new error message is shown. Otherwise, a new game is started and the custom word list text areas on everyone's browser is updated to the normalized version of the list.

I didn't want to put too much effort into keeping the word list in sync between the different players. Also, this implementation means the "Word Pool" numbers are incorrect until a new game has actually been started with the custom word list.
